apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  users: |2
    {{ .Values.creds }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}
spec:
  basicAuth:
    secret: {{ .Release.Name }}