apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: traefik
  labels:
    release: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.host }}`)
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}
      services:
        - name: {{ .Release.Name }}
          port: 80
